// Have the function FirstFactorial(num) take the num parameter being passed and return the factorial of it. For example: if num = 4, then your program should return (4 * 3 * 2 * 1) = 24. For the test cases, the range will be between 1 and 18 and the input will always be an integer.

function firstFactorial(num) {
	if (num === 0 || num == 1) {
		return 1;
	} else {
		return num * firstFactorial(num - 1);
	}
}
// console.log(firstFactorial(1));

// Have the function FirstReverse(str) take the str parameter being passed and return the string in reversed order. For example: if the input string is "Hello World and Coders" then your program should return the string sredoC dna dlroW olleH.

function firstReverse(str) {
	// const makeArr = str.split("");
	// makeArr.reverse();
	// return makeArr.join("");

	// const reverseString = str => {
	// 	let revStr = "";

	// 	for (let i = str.length - 1; i >= 0; i--)
	// 	{
	// 		revStr = str[i] + revStr;
	// 	}

	// 	return revStr;
	// };

	////

	return str.split("").reduce((prevEl, currentEl) => {
		return prevEl + currentEl;
	});
}

// console.log(firstReverse("Watch"));
// // accumulator = ''
// nextValue   = 'h'
// index       = 0
// nextValue + accumulator = 'h'

// Increment index = 1

// accumulator = 'h'
// nextValue = 'e'
// index = 1
// nextValue + accumulator = 'eh'

// console.log(firstReverse("hello"));

// Have the function SimpleAdding(num) add up all the numbers from 1 to num. For example: if the input is 4 then your program should return 10 because 1 + 2 + 3 + 4 = 10. For the test cases, the parameter num will be any number from 1 to 1000.

// function SimpleAdding(num) {
// 	if (num === 1) {
// 		return 1;
// 	} else {
// 		return num + SimpleAdding(num - 1);
// 	}
// }

const simpleAdding = num => {
	myArr = [];

	for (let i = 0; i <= num; i++) {
		myArr.push(i);
	}

	const finArr = myArr.reduce((acc, current) => acc + current);
	return finArr;
};

// console.log(simpleAdding(140));

// Have the function LetterCapitalize(str) take the str parameter being passed and capitalize the first letter of each word. Words will be separated by only one space.

const LetterCapitalize = str => {
	const wordArr = str.split(" ");

	for (let i = 0, n = wordArr.length; i < n; i++) {
		wordArr[i] = wordArr[i][0].toUpperCase() + wordArr[i].slice(1);
	}
	str = wordArr.join(" ");

	return str;
};

//console.log(LetterCapitalize("hello there"));

// Add all the natural numbers below one thousand that are multiples of 3 or 5.

const sumOfMultiple = limit => {
	let i = 0;
	let sum = 0;

	for (i = 1; i < limit; i++) {
		if (i % 3 === 0 || i % 5 === 0) {
			sum += i;
		}
	}
	return sum;
};

//console.log(sumOfMultiple(1000));

//Find the sum of the even-valued terms in the Fibonacci sequence whose values do not exceed four million.
//Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even - valued terms.

const factorialNumber = num => {
	let factorial = 1;

	for (let i = 1; i <= num; i++) {
		factorial = factorial * i;
	}

	return factorial;
};

// console.log(factorialNumber(4));

// console.log(reverseString("Watch"));

// Validate a palindrome
// Palindrome it's a word that reads the same when it's backwards

const isPalindrome = str =>
	str ===
	str
		.split("")
		.reverse()
		.join("");

// console.log(isPalindrome("madam"));

// CHALLENGE 3 : REVERSE AN INTEGER
// Return an integer in reverse

function reverseInt(int) {
	const revInt = int
		.toString()
		.split("")
		.reverse()
		.join("");

	return parseInt(revInt);
}

// console.log(reverseInt(43561));

// CHALLENGE 4: CAPITIALIZE LETTERS
// Return a string with the first letter of every word capitalized

const capitalizeLetters = str => {
	return str
		.toLowerCase()
		.split(" ")
		.map(word => {
			return word[0].toUpperCase() + word.substr(1);
		})
		.join(" ");
	// const strArr = str.toLowercase().split(" ");

	// for (let i = 0; i < str.length; i++) {
	// 	strArr[i] =
	// 		strArr[i].substring(0, 1).toUpperCase() + strArr[i].substring(1);
	// }

	// return strArr.join(" ");
};

// console.log(capitalizeLetters("i love javascript"));

// CHALLENGE 5 : MAX CHARACTER
// Return the character that is most common in a string

// CHALLENGE 6 : FIZZBUZZ
// Write a program that prints all the numbers from 1 to 100. For multiples of 3, instead of the number, print "Fizz", for multiples of 5, print "buzz". For numbers which are multiples of both 3 and 5, print "FizzBuzz".

const fizzBuzz = () => {
	for (let i = 1; i <= 100; i++) {
		if (i % 3 === 0 && i % 5 === 0) {
			console.log("FizzBuzz");
		} else if (i % 3 === 0) {
			console.log("Fizz");
		} else if (i % 5 === 0) {
			console.log("Buzz");
		} else {
			console.log(i);
		}
	}
};

fizzBuzz();
